using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Creobit.Backend.AndroidPlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.AppStore")]
[assembly: InternalsVisibleTo("Creobit.Backend.AppStorePlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.CustomPlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.GooglePlay")]
[assembly: InternalsVisibleTo("Creobit.Backend.GooglePlayPlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.IosPlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.PlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.Steam")]
[assembly: InternalsVisibleTo("Creobit.Backend.SteamPlayFab")]
[assembly: InternalsVisibleTo("Creobit.Backend.Unity")]
[assembly: InternalsVisibleTo("Creobit.Backend.Test.PlayMode")]
[assembly: InternalsVisibleTo("Creobit.Backend.Test.EditMode")]
